const $=s=>document.querySelector(s), iso=d=>d.toISOString().slice(0,10), today=()=>iso(new Date()), tomorrow=()=>{let d=new Date();d.setDate(d.getDate()+1);return iso(d)};
let D=JSON.parse(localStorage.getItem('ssa')||'null')||{tasks:[{id:1,name:'Math homework',due:today(),mins:45,p:3,done:false},{id:2,name:'Science reading',due:today(),mins:30,p:2,done:false}],commit:[],trial:null};
const save=()=>localStorage.setItem('ssa',JSON.stringify(D)), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page='today', month=new Date(), titles={today:['Today','Your plan, without the guesswork.'],calendar:['Calendar','Your month at a glance.'],tasks:['Tasks','Assignments and deadlines.'],week:['Week','Your next seven days.'],planner:['Planner AI','Only for changing your schedule.'],assistant:['AI Assistant','A general student assistant for school, planning, and everyday questions.'],settings:['Settings','Your preferences.']};
function task(x){return `<div class=task><div><b>${esc(x.name)}</b><div class=muted>${x.due} · ${x.mins} min · ${x.p==3?'High':x.p==2?'Normal':'Low'}</div></div><button onclick="toggle(${x.id})">${x.done?'Undo':'Complete'}</button></div>`}
function toggle(id){let x=D.tasks.find(x=>x.id==id);x.done=!x.done;save();render()}
function render(){let t=titles[page];$('#title').textContent=t[0];$('#sub').textContent=t[1];document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page==page));if(page==='today')todayPage();if(page==='tasks')tasksPage();if(page==='calendar')calendarPage();if(page==='week')weekPage();if(page==='planner')plannerPage();if(page==='assistant')assistantPage();if(page==='settings')settingsPage()}
function todayPage(){let a=D.tasks.filter(x=>!x.done).sort((a,b)=>a.due.localeCompare(b.due)||b.p-a.p);$('#page').innerHTML=`<div class=grid><div class=card><div class=muted>Open tasks</div><div class=stat>${a.length}</div></div><div class=card><div class=muted>Due today</div><div class=stat>${a.filter(x=>x.due==today()).length}</div></div><div class=card><div class=muted>Workload</div><div class=stat>${a.reduce((n,x)=>n+x.mins,0)}m</div></div></div><div class=card><h2>Priorities</h2>${a.map(task).join('')||'<p class=muted>You are caught up.</p>'}</div>`}
function tasksPage(){$('#page').innerHTML=`<div class=card><h2>All tasks</h2>${D.tasks.map(task).join('')}</div>`}
function calendarPage(){let y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),s=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class=dow>${x}</div>`).join('');for(let i=0;i<start;i++)s+='<div class=day></div>';for(let d=1;d<=days;d++){let z=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=D.tasks.filter(x=>x.due==z&&!x.done).map(x=>x.name);s+=`<div class="day ${z==today()?'today':''}"><b>${d}</b>${ev.map(x=>`<div class=event>${esc(x)}</div>`).join('')}</div>`}$('#page').innerHTML=`<div class=card><div style="display:flex;justify-content:space-between;align-items:center"><button onclick="month.setMonth(month.getMonth()-1);render()">←</button><h2>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button onclick="month.setMonth(month.getMonth()+1);render()">→</button></div><div class=calendar>${s}</div></div>`}
function weekPage(){let s='';for(let i=0;i<7;i++){let d=new Date();d.setDate(d.getDate()+i);let z=iso(d),a=D.tasks.filter(x=>x.due==z&&!x.done);s+=`<div class=card><b>${d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</b><p class=muted>${a.length?a.map(x=>esc(x.name)).join(' · '):'No tasks due'}</p></div>`}$('#page').innerHTML=s}
function plannerPage(){$('#page').innerHTML=`<div class=card chat><div id=msgs class=messages><div class="msg bot">I only change your schedule. Tell me a real change like “add soccer at 6 PM,” “practice was cancelled,” “I finished science,” or “add 30 minutes of math tomorrow.”</div></div><div class=chips><button class=chip data-q="What should I do first?">What first?</button><button class=chip data-q="Practice was cancelled">Practice cancelled</button><button class=chip data-q="Add 30 minutes of math tomorrow">Add task</button></div><div class=chatrow><input id=pi placeholder="Tell me what changed..."><button id=ps>Send</button></div></div>`;$('#ps').onclick=sendPlanner;$('#pi').onkeydown=e=>e.key==='Enter'&&sendPlanner();document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('#pi').value=b.dataset.q;sendPlanner()})}
function addMsg(id,t,c){let b=$(id);b.insertAdjacentHTML('beforeend',`<div class="msg ${c}">${esc(t)}</div>`);b.scrollTop=b.scrollHeight}
function sendPlanner(){let i=$('#pi'),q=i.value.trim();if(!q)return;addMsg('#msgs',q,'user');i.value='';addMsg('#msgs',plannerAnswer(q.toLowerCase()),'bot');save()}
function plannerAnswer(q){if(q.includes('cancel')&&q.includes('practice')){D.commit=D.commit.filter(x=>!x.name.toLowerCase().includes('soccer'));return'Done. I removed the soccer practice from your commitments and freed that time.'}if(q.includes('what should')||q.includes('what first')){let x=D.tasks.filter(x=>!x.done).sort((a,b)=>a.due.localeCompare(b.due)||b.p-a.p)[0];return x?`Start with ${x.name}. It is due ${x.due} and takes about ${x.mins} minutes.`:'You have no unfinished tasks.'}let f=D.tasks.find(x=>q.includes(x.name.toLowerCase())&&(q.includes('finish')||q.includes('done')));if(f){f.done=true;return`Done. I marked ${f.name} complete.`}let m=q.match(/add (\d+) minutes? of (.+?)( tomorrow)?$/);if(m){D.tasks.push({id:Date.now(),name:m[2],due:m[3]?tomorrow():today(),mins:+m[1],p:2,done:false});return`Added ${m[2]} for ${m[3]?'tomorrow':'today'} for ${m[1]} minutes.`}return'Tell me a concrete schedule change and I will update the saved plan.'}
function assistantPage(){$('#page').innerHTML=`<div class=assistant><div class=card chat><div id=amsgs class=messages><div class="msg bot">I’m the general StudentSchedule AI assistant. I can help with school questions, studying, brainstorming, planning, writing, and everyday student problems. I’ll explain things step-by-step when useful and use your saved tasks when relevant.<br><br>This is a local assistant built into the free website, so it is not a full cloud model like ChatGPT and has no live web access.</div></div><div class=chips><button class=chip data-aq="Help me plan tonight">Plan tonight</button><button class=chip data-aq="Give me a study strategy">Study strategy</button><button class=chip data-aq="What should I work on first?">What first?</button></div><div class=chatrow><input id=ai placeholder="Ask me anything..."><button id=as>Send</button></div></div><div class=card><h2>Assistant style</h2><p>Clear, practical, calm, student-focused, and step-by-step when needed.</p><p class=muted>Planner AI is kept separate so this assistant can answer general questions without accidentally changing your calendar.</p></div></div>`;$('#as').onclick=sendAI;$('#ai').onkeydown=e=>e.key==='Enter'&&sendAI();document.querySelectorAll('[data-aq]').forEach(b=>b.onclick=()=>{$('#ai').value=b.dataset.aq;sendAI()})}
function sendAI(){let i=$('#ai'),q=i.value.trim();if(!q)return;addMsg('#amsgs',q,'user');i.value='';addMsg('#amsgs',aiAnswer(q),'bot')}
function aiAnswer(q){let l=q.toLowerCase();if(l.includes('plan tonight')||l.includes('what should')){let x=D.tasks.filter(x=>!x.done).sort((a,b)=>a.due.localeCompare(b.due)||b.p-a.p)[0];return x?`Based on your saved tasks, start with ${x.name}. It is due ${x.due} and takes about ${x.mins} minutes. Tell me how many minutes you have and I can break tonight into smaller blocks.`:'You are caught up.'}if(l.includes('study'))return'Use active practice: identify the weakest topic, try problems without notes, check mistakes, write why each mistake happened, then retry similar problems. Short focused blocks are easier to fit into a busy schedule.';if(l.includes('hello')||l=='hi')return'Hi. Tell me what you are trying to do and I will help you break it down.';if(l.includes('who are you'))return'I am the general StudentSchedule AI assistant. I am designed to be clear, practical, and student-focused. I can use the information saved in this app, but I am not a full cloud AI model.';return'I can help with that. Give me the goal, what you already know, and any deadline or time limit. I will work through it with you rather than just giving a one-line answer.'}
function settingsPage(){$('#page').innerHTML='<div class=card><h2>Settings</h2><p class=muted>Your tasks and planner data are stored locally in this browser.</p></div>'}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});$('#add').onclick=()=>{$('#modal').classList.remove('hidden');$('#due').value=today()};$('#cancel').onclick=()=>$('#modal').classList.add('hidden');$('#save').onclick=()=>{let n=$('#name').value.trim();if(!n)return;D.tasks.push({id:Date.now(),name:n,due:$('#due').value||today(),mins:+$('#mins').value||30,p:+$('#pri').value,done:false});save();$('#modal').classList.add('hidden');render()};$('#trialBtn').onclick=()=>{if(!D.trial){D.trial=Date.now();save();$('#trialText').textContent='Pro trial active for 3 days.';$('#trialBtn').textContent='Trial Active'}else alert('After the 3-day trial, connect a parent/guardian payment checkout for Pro.')}};render();